# Site configuration (MyST / Jupyter Book)
title: 2024 UW–Madison Open Source Program Office Survey
author: UW–Madison Data Science Institute
logo: images/header-logo.png   # optional if present
only_build_toc_files: true

# Repository links (adjust if you keep same repo)
repository:
  url: https://github.com/UW-Madison-DSI/open_source_survey_results
  path_to_book: .
  branch: main

html:
  favicon: images/ospo-favicon.png  # optional
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  extra_navbar: ""    # or HTML string
  extra_footer: |
    <p>© UW–Madison Data Science Institute</p>

sphinx:
  extra_extensions:
    - myst_nb
    - sphinx_copybutton
    - sphinx_design
  config:
    myst_enable_extensions:  # enable nice extras
      - colon_fence
      - dollarmath
      - deflist
      - linkify
      - substitution
      - tasklist
    nb_execution_mode: "off"   # turn off notebook execution by default
    nb_render_priority:
      html:
        - application/vnd.plotly.v1+json
        - text/html
        - image/svg+xml
        - image/png
        - image/jpeg
        - text/markdown
        - text/plain
