# Book settings
title: Open Source Survey Results
author: UW-Madison Data Science Institute
logo: _static/logo.png
copyright: "© 2025 UW–Madison Data Science Institute"

# Execute notebooks
execute:
  execute_notebooks: "force"

# LaTeX/PDF
latex:
  latex_documents:
    targetname: book.tex

# Substitutions (edit once; reuse everywhere)
myst_substitutions:
  uni_name: "University of Wisconsin–Madison"
  today: "September 2025"
  year: "2024"
  contact_email: "ospo@datascience.wisc.edu"
  privacy_url: "https://www.wisconsin.edu/privacy-policy/"
  dsi_url: "https://datascience.wisc.edu/"
  libs_url: "https://www.library.wisc.edu/"

# Where the book lives
repository:
  url: https://github.com/UW-Madison-DSI/open_source_survey_results_myst
  path_to_book: "."
  branch: main

# Site & theme options
html:
  extra_css:
    - _static/custom.css
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  navbar_number_sections: false
  extra_footer: |
    <div class="custom-footer" role="contentinfo">
      <div class="footer-grid">
        <!-- New left column with UW logo -->
        <div class="footer-col">
          <a href="https://www.wisc.edu/" target="_blank" rel="noopener">
            <img src="_static/uw-crest-black-print.svg" 
                 alt="UW–Madison"
                 style="max-height:80px; width:auto; display:block; margin:auto;"/>
          </a>
        </div>

        <div class="footer-col">
          <h4>COMMUNITY</h4>
          <p><a href="https://datascience.wisc.edu/" target="_blank" rel="noopener">Data Science Institute</a></p>
          <p><a href="https://datascience.wisc.edu/data-science-hub/" target="_blank" rel="noopener">Data Science Hub</a></p>
          <p><a href="https://www.library.wisc.edu/" target="_blank" rel="noopener">UW–Madison Libraries</a></p>
          <p><a href="https://curioss.wisc.edu/" target="_blank" rel="noopener">CURIOSS</a></p>
          <p><a href="https://numfocus.org/" target="_blank" rel="noopener">NumFOCUS</a></p>
        </div>

        <div class="footer-col">
          <h4>QUICK LINKS</h4>
          <p><a href="https://groups.google.com/g/ospo-uw" target="_blank" rel="noopener">Join Our OSPO Google Group</a></p>
          <p><a href="https://datascience.wisc.edu/research-bazaar/" target="_blank" rel="noopener">Data Science Research Bazaar</a></p>
          <p><a href="https://datascience.wisc.edu/newsletter/" target="_blank" rel="noopener">Data Science @ UW Newsletter</a></p>
        </div>

        <div class="footer-col">
          <h4>CONTACT US</h4>
          <p>Email: <a href="mailto:ospo@datascience.wisc.edu">ospo@datascience.wisc.edu</a></p>
          <p>
            <a href="https://x.com/datascience_uw" target="_blank" rel="noopener" style="display:flex;align-items:center;gap:6px;">
              <!-- Inline SVG: Twitter bird -->
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 248 204" fill="currentColor">
                <path d="M221.95 51.29c.15 2.17.15 4.34.15 6.53 0 66.73-50.8 143.63-143.63 143.63-28.54 0-55.1-8.37-77.39-22.82 4.02.48 8.06.72 12.14.72 23.7 0 45.53-8.07 62.83-21.72-22.15-.41-40.83-15-47.33-35.07a50.51 50.51 0 0 0 22.7-.86c-23.4-4.7-40.92-25.37-40.92-50.18v-.64a50.7 50.7 0 0 0 22.9 6.32c-13.6-9.1-22.54-24.6-22.54-42.15 0-9.27 2.48-17.94 6.82-25.4a143.35 143.35 0 0 0 104.07 52.8c-7.2-30.87 16.6-55.6 44.02-55.6 12.97 0 24.68 5.47 32.91 14.24 10.26-2.02 19.91-5.75 28.6-10.91-3.37 10.5-10.49 19.34-19.8 24.94 9.13-1.08 17.84-3.52 25.9-7.1-6.06 9.05-13.71 17.02-22.54 23.38z"/>
              </svg>
              Follow us on Twitter
            </a>
          </p>
        </div>
      </div>

      <div class="footer-bottom-row">
        <p>© 2024 Board of Regents of the <a href="https://www.wisconsin.edu/" target="_blank" rel="noopener">University of Wisconsin System</a> |
        <a href="https://www.wisconsin.edu/privacy-policy/" target="_blank" rel="noopener">Privacy notice</a> |
        Feedback, questions or accessibility issues: <a href="mailto:ospo@datascience.wisc.edu">ospo@datascience.wisc.edu</a></p>
      </div>
    </div>


# MyST extensions
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

# Sphinx
sphinx:
  config:
    html_static_path: ['_static']
    html_css_files: ['custom.css']